Feat: mouse rotation
ft-vox/prototype-0 pull request #1
Opened 2024-10-10 16:33 UTC by jeekpark

마우스 움직임에 따라 카메라 뷰가 회전되는 간단한 기능 추가

2024-10-10 22:54 UTC, mjy9088 requested changes
platform-dependent한 dependency는 optional로 빼서 웹/맥 버전도 일단 마우스 관련 기능 없이라도 돌아가게 하면 좋을 것 같습니다!

2024-10-10 22:54 UTC, mjy9088 commented on lib/Cargo.toml
> +winapi = { version = "0.3", features = ["winuser"] }
```toml
[target.'cfg(windows)'.dependencies]
winapi = ...
```
winapi는 이 섹션에 있어야 될 것 같습니다.

2024-10-10 22:54 UTC, mjy9088 commented on lib/src/lib.rs
> +use winapi::um::winuser::SetCursorPos;
마찬가지로 이 부분도 `#[cfg(...)]` 안에 들어가야 할 것 같습니다.
```rs
#[cfg(windows)]
use winapi::...
```

2024-10-10 22:55 UTC, mjy9088 commented on lib/src/lib.rs
> +                            unsafe {
이 부분은 나중에 별도의 함수로 빼는 게 좋겠네요 :)

2024-10-11 12:52 UTC, jeekpark commented
플랫폼 의존성 해결하는 코드 적용했습니다.

별도에 함수로 빼는건, 나중에 모듈화할때 하는 게 좋을 것 같아서 run 함수 내에 일단 냅뒀습니다.

2024-10-11 13:08 UTC, mjy9088 approved these changes

2024-10-11 13:09 UTC, mjy9088 commented
고생하셨습니다 :)

2024-10-11 13:20 UTC, merged